# Generated by Django 4.0.3 on 2022-03-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('kakao_id', models.CharField(max_length=100)),
                ('point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gender')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
