# Generated by Django 4.0.3 on 2022-03-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_remove_product_published_at_and_more'),
        ('orders', '0002_order_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='series',
        ),
        migrations.CreateModel(
            name='OrderSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.series')),
            ],
            options={
                'db_table': 'order_series',
            },
        ),
    ]
